### ISSUE TITLE
Include `System.ComponentModel.Annotations` package to support .NET Standard 2.0

### ISSUE THREAD

**Issue by Turnerj** [vivainio/FastExpressionKit#1]
Hey - I stumbled across your repository from [your recent post on DEV](https://dev.to/vivainio/notes-from-a-local-nuget-package-development-workflow-53c1) and it caught my eye about how you mentioned that `System.ComponentModel.DataAnnotations` is missing from .NET Standard 2.0 - while you are right, you can still target .NET Standard 2.0 by including the [`System.ComponentModel.Annotations`](https://www.nuget.org/packages/System.ComponentModel.Annotations) package.

That package includes the attributes you were expecting under `System.ComponentModel.DataAnnotations`.

I do this in my own library here: https://github.com/TurnerSoftware/MongoFramework/blob/d8bda7f76d505f668b7dd4339849a91e51347422/src/MongoFramework/MongoFramework.csproj#L3-L16

**Comment by vivainio** [comment]
Thanks, I'll try out how this interops with our codebase

**Comment by vivainio** [comment]
The whole lib is now netstandard2.0, thanks for the tip!
